########## Testcase 0: Failed ##########
Expected Output: 
rehana 1
karan 3
murthy 2
rajiv 5
kalyani 4
rehana 1
murthy 2
karan 3
kalyani 4
rajiv 5

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 52, in main
    getReserve(tokens[1])
  File "reservation.py", line 14, in getReserve
    print(person+" "+ roomnum)
TypeError: must be str, not int
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
kiran 2
murthy 1
rajiv 3
kalyani 4
kumar 5
All Rooms are reserved
murthy 1
kiran 2
rajiv 3
kalyani 4
kumar 5

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
kiran 2
murthy 1
rajiv 3
kalyani 4
kumar 5
All Rooms are reserved
All Rooms are reserved
murthy 1
kiran 2
rajiv 3
kalyani 4
kumar 5

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
All Rooms are reserved
murthy 1
kiran 2
kalyani 3
kumar 4
swathi 5

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
Added 2 more rooms
alekhya 6
manasa 7
murthy 1
kiran 2
kalyani 3
kumar 4
swathi 5
alekhya 6
manasa 7

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
kumar 5
murthy 1
kiran 2
kalyani 3
kumar 4
kumar 5
kumar now has no reservations.
murthy 1
kiran 2
kalyani 3
Added 5 more rooms
alekhya 6
manasa 4
kumar 5
karthik 7
manohar 8
swetha 9
reddy 10
murthy 1
kiran 2
kalyani 3
manasa 4
kumar 5
alekhya 6
karthik 7
manohar 8
swetha 9
reddy 10

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

########## Testcase 6: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
swathi 5
murthy 1
kiran 2
kalyani 3
kumar 4
swathi 5
kumar now has no reservations.
murthy 1
kiran 2
kalyani 3
swathi 5
Added 2 more rooms
alekhya 6
manasa 4
kumar 7
murthy 1
kiran 2
kalyani 3
manasa 4
swathi 5
alekhya 6
kumar 7

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

########## Testcase 7: Failed ##########
Expected Output: 
kiran 2
murthy 1
Room is already reserved
kalyani 3
kumar 4
kumar 5
murthy 1
kiran 2
kalyani 3
kumar 4
kumar 5
kumar now has no reservations.
murthy 1
kiran 2
kalyani 3
Added 5 more rooms
alekhya 6
manasa 4
kumar 5
karthik 7
manohar 8
swetha 9
reddy 10
murthy 1
kiran 2
kalyani 3
manasa 4
kumar 5
alekhya 6
karthik 7
manohar 8
swetha 9
reddy 10

Your Output: 
Traceback (most recent call last):
  File "reservation.py", line 60, in <module>
    main()  
  File "reservation.py", line 54, in main
    getN(tokens[1], tokens[2])
  File "reservation.py", line 24, in getN
    for room in sorted(lis):
NameError: name 'lis' is not defined
----------------------------------------

